app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hwi_oauth_connect:
    path: /spotify/logga-in
    defaults: { _controller: HWIOAuthBundle:Connect:connect }
hwi_oauth_service_redirect:
    path: /spotify/connect/{service}
    defaults: { _controller: HWIOAuthBundle:Connect:redirectToService }
spotify_login:
    path: /spotify/logga-in/check
logout:
    path: /spotify/logga-ut

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
