app:
    resource: "@AppBundle/Controller/"
    type:     annotation
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /spotify/logga-in
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /spotify/connect
spotify_login:
    path: /spotify/logga-in/check
logout:
    path: /spotify/logga-ut
