# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sr_client:
        class: AppBundle\WebService\SR\SrWebServiceClient
        arguments: ["@ci.restclient", "@jms_serializer"]
    spotify_track_finder:
        class: AppBundle\Service\SpotifyTrackFinder
        arguments: ["@spotify.web_api"]
    spotify_track_converter:
        class: AppBundle\Service\SrToSpotifyTrackConverter
        arguments: ["@spotify_track_finder"]
    twig.extensions.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    spotify.session:
        class: SpotifyWebAPI\Session
        arguments: ["%spotify.client_id%", "%spotify.client_secret%", "%spotify.redirect_uri%"]
    spotify.web_api:
        class: AppBundle\Service\UserAwareSpotifyWebApi
        calls:
            - [ setTokenStorage, ["@security.token_storage"]]
    app.spotify_repository:
      class: AppBundle\Entity\Repository\SpotifyUserRepository
      factory: ["@doctrine.orm.default_entity_manager", getRepository]
      arguments: [AppBundle\Entity\SpotifyUser]
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    app.spotify_oauth_user_provider:
        class: AppBundle\Security\User\SpotifyOAuthUserProvider
        arguments: ["@app.spotify_repository", "@doctrine.orm.default_entity_manager", "@spotify.web_api"]
