# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    hwi_oauth.authentication.entry_point.oauth.class: AppBundle\Security\Http\EntryPoint\AjaxEntryPoint

services:
    sr_client:
        class: AppBundle\WebService\SR\SrWebServiceClient
        arguments: ["@ci.restclient", "@jms_serializer"]

    spotify.value_object_builder:
        class: AppBundle\WebService\Spotify\ValueObjectBuilder
    spotify.track_finder:
        class: AppBundle\WebService\Spotify\TrackFinder
        arguments: ["@spotify.web_api", "@spotify.value_object_builder"]
    spotify.track_converter:
        class: AppBundle\Service\SrToSpotifyTrackConverter
        arguments: ["@spotify.track_finder"]
    spotify.playlist_manager:
        class: AppBundle\WebService\Spotify\PlaylistManager
        arguments: ["@spotify.web_api", "@spotify.value_object_builder"]

    spotify.session:
        class: SpotifyWebAPI\Session
        arguments: ["%spotify.client_id%", "%spotify.client_secret%", "%spotify.redirect_uri%"]
    spotify.web_api:
        class: AppBundle\Service\UserAwareSpotifyWebApi
        calls:
            - [ setTokenStorage, ["@security.token_storage"]]

    twig.extensions.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    app.spotify_user_repository:
      class: AppBundle\Entity\Repository\SpotifyUserRepository
      factory: ["@doctrine.orm.default_entity_manager", getRepository]
      arguments: [AppBundle\Entity\SpotifyUser]

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    app.spotify_oauth_user_provider:
        class: AppBundle\Security\User\SpotifyOAuthUserProvider
        arguments: ["@app.spotify_user_repository", "@doctrine.orm.default_entity_manager", "@spotify.web_api", "@hwi_oauth.resource_owner.spotify"]
